name: meson

on:
  push:
    paths:
      - "**.c"
      - "**.h"
      - "meson.build"
      - "tests/**"
  pull_request:
    paths:
      - "**.c"
      - "**.h"
      - "meson.build"
      - "tests/**"

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: sudo apt-get install -y libelf-dev libpopt-dev meson ninja

    - name: Configure
      run: meson setup builddir/
      env:
        CC: gcc

    - name: Test
      run: meson test -C builddir/ -v

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: meson-testlog
        path: builddir/meson-logs/testlog.txt
